# docker-compose.yml
version: "3.8"

services:
  db:
    image: supabase/postgres:14.1.0.21
    container_name: senu_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - senu_db_data:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command:
      - "postgres"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"

    ports:
      - "5432:5432" # Expose port 5432 for external access
    restart: always

  supabase-auth:
    image: supabase/gotrue:v2.160.1-rc.1
    container_name: senu_supabase_auth
    depends_on:
      - db
    environment:
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_API_HOST: 0.0.0.0
      API_EXTERNAL_URL: http://localhost:9999
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_SMTP_HOST: ${SMTP_HOST}
      GOTRUE_SMTP_PORT: ${SMTP_PORT}
      GOTRUE_SMTP_USER: ${SMTP_USER}
      GOTRUE_SMTP_PASS: ${SMTP_PASS}
      GOTRUE_SMTP_ADMIN_EMAIL: ${ADMIN_EMAIL}
    ports:
      - "9999:9999"

  supabase-rest:
    image: postgrest/postgrest:v9.0.0
    container_name: senu_supabase_rest
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgresql://postgres:postgres@db:5432/postgres
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_ANON_ROLE: anon
      PGRST_DB_ANON_ROLE: anon

    ports:
      - "3000:3000"

  app:
    build:
      context: .
      dockerfile: Dockerfile # Ensure you have a Dockerfile for your app
    container_name: senu_app
    ports:
      - "8000:8000" # Expose port 8000 for external access
    volumes:
      - senu_app_data:/app
    environment:
      - APP_SQL_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - supabase-auth
      - supabase-rest

  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: senu_phoenix
    depends_on:
      - db
    ports:
      - 6006:6006 # Expose port 6006 for external access
      - 4317:4317 # Expose port 4317 for external access
      - 9090:9090 # Expose port 9090 for external access
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: senu_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: amagdy3@gmail.com
      PGADMIN_DEFAULT_PASSWORD: amagdy3
    ports:
      - "5050:80" # Expose port 5050 for external access
    depends_on:
      - db

volumes:
  senu_db_data:
    name: senu_db_data
  senu_app_data:
    name: senu_app_data
