version: '3.8'
services:
  app:
    volumes:
      - .:/workspace:cached
      - ./venv:/workspace/venv:cached
    command: /bin/sh -c "source /workspace/venv/bin/activate && while sleep 1000; do :; done"
