version: '3.8'
services:
  app:
    volumes:
      - .:/workspace:cached
      - ./venv:/workspace/venv:cached
    command: /bin/sh -c "source /workspace/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8000"
