version: '3.8'
services:
  app:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace:cached
      - ./venv:/workspace/venv:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
