version: "3.8"
services:
  app:
    volumes:
      - .:/workspace:cached
    ports:
      - "8008:8008"
    environment:
      - APP_SQL_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    command: /bin/sh -c "chmod +x /workspace/.devcontainer/setup.sh && bash /workspace/.devcontainer/setup.sh"
